kind: Deployment
apiVersion: apps/v1
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: jasminengn/email
          envFrom:
            - configMapRef:
                name: email-configmap
            - secretRef:
                name: email-secret
